"""DEV-09-CB CodeBuddy tests: signed checkpoint generation and independent
verification of the audit v1 chain (A-03/A-04/A-11 signature portions).

Test keys are generated by openssl inside TemporaryDirectory; key contents are
never displayed, logged, or committed.
"""
