'use strict';
const $=id=>document.getElementById(id);
let session=null,historyId=null;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
async function api(path,data){const options={credentials:'same-origin',headers:{}};if(data!==undefined){options.method='POST';options.headers['Content-Type']='application/json';options.headers['X-CSRF-Token']=session?.csrf||'';options.body=JSON.stringify(data);}const response=await fetch(path,options);const result=await response.json();if(!response.ok)throw Error(result.error||'Request unavailable');return result;}
function show(name){for(const id of ['login','workspace','other'])$(id).hidden=id!==name;$('status').textContent='';}
function identity(){const box=$('identity');box.replaceChildren(el('span',session.actor));const logout=el('button','Switch demo identity');logout.onclick=async()=>{await api('/api/logout',{});session=null;historyId=null;$('answer').replaceChildren();$('other').replaceChildren();$('auditNav').hidden=true;$('sourcesNav').hidden=true;box.textContent='Not signed in';show('login');};box.append(logout);$('auditNav').hidden=session.actor!=='auditor';$('sourcesNav').hidden=session.actor!=='auditor';show('workspace');}
async function preview(id){try{const e=await api('/api/evidence/'+encodeURIComponent(id));const body=$('previewBody');body.replaceChildren(el('h2',e.title),el('p',e.text),el('p','Version '+e.version,'muted'),el('pre',JSON.stringify(e.locator,null,2)),el('p',e.source_url,'muted'));$('preview').showModal();}catch(e){$('status').textContent='Evidence is unavailable or has changed. Ask again for current sources.';}}
function renderAnswer(answer,target=$('answer')){target.replaceChildren();if(answer.unavailable){target.append(el('p',answer.message,'notice'));return;}const grid=el('div',undefined,'receipt'),main=el('div',undefined,'panel'),side=el('aside',undefined,'panel');const head=el('div',undefined,'receipt-head');head.append(el('h2','Evidence-backed excerpts'),el('span','FAKE MODEL','tag'));main.append(head);for(const c of answer.claims){const block=el('div',undefined,'claim');block.append(el('p',c.text));for(const id of c.evidence_ids){const b=el('button',id,'citation');b.onclick=()=>preview(id);block.append(b);}main.append(block);}for(const u of answer.uncertainties)main.append(el('p',u,'notice'));main.append(el('p','Receipt '+answer.request_id,'muted'));side.append(el('h3','Source evidence'));for(const e of answer.evidence){const card=el('div',undefined,'source-card');card.append(el('span',e.source,'source-name'));const b=el('button',e.title);b.onclick=()=>preview(e.evidence_id);card.append(el('p'),b,el('p','Version '+e.version+' · '+JSON.stringify(e.locator)),el('p','Source updated '+new Date(e.source_updated_at).toLocaleString()),el('p','Indexed '+new Date(e.indexed_at).toLocaleString()));side.append(card);}if(!answer.evidence.length)side.append(el('p','No supporting evidence is available for this answer.'));grid.append(main,side);target.append(grid);}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{session=await api('/api/demo/login',{user:$('user').value});identity();}catch(err){$('status').textContent=err.message;}};
$('queryForm').onsubmit=async e=>{e.preventDefault();$('ask').disabled=true;$('status').textContent='Checking access and assembling evidence…';try{const data={question:$('question').value};if(historyId)data.history_id=historyId;const a=await api('/api/query',data);historyId=a.request_id;renderAnswer(a);$('status').textContent='Answer recorded. Source excerpts are from synthetic fixtures.';}catch(err){$('answer').replaceChildren();$('status').textContent=err.message;}finally{$('ask').disabled=false;}};
for(const b of document.querySelectorAll('[data-question]'))b.onclick=()=>{$('question').value=b.dataset.question;$('question').focus();};
$('workspaceNav').onclick=()=>show(session?'workspace':'login');
$('historyNav').onclick=async()=>{if(!session)return;show('other');$('other').replaceChildren(el('h1','Recent answers'),el('p','Access and versions are checked again before answers are displayed.','lede'));try{const result=await api('/api/history');for(const a of result.history){const item=el('div',undefined,'history-item');renderAnswer(a,item);$('other').append(item);}if(!result.history.length)$('other').append(el('p','No answers yet.'));}catch(e){$('status').textContent=e.message;}};
$('sourcesNav').onclick=async()=>{show('other');$('other').replaceChildren(el('h1','Source coverage'),el('p','Fixture adapters are active. Live integrations are blocked pending explicit authorization.','lede'));try{const r=await api('/api/sources/status');for(const s of r.sources){const card=el('div',undefined,'panel');card.append(el('h2',s.source),el('p','Status: '+s.status),el('p','Live: '+s.live),el('p',s.authority));$('other').append(card);}}catch(e){$('status').textContent=e.message;}};
$('auditNav').onclick=()=>{show('other');const root=$('other');root.replaceChildren(el('h1','Audit explorer'),el('p','Scoped to eng_a, eng_b and product_ops. Events describe application activity, not proof that a person read the answer.','lede'));const form=el('form',undefined,'audit-form'),input=el('input');input.setAttribute('aria-label','Audit inquiry');input.value='Show everything jdoe accessed related to payment-service in the last 30 days.';const button=el('button','Find events','primary');form.append(input,button);const output=el('div');root.append(form,output);let filters=null;async function display(result,append=false){if(!append)output.replaceChildren(el('pre',JSON.stringify(result.filters,null,2)),el('p',result.total+' exact matching events · snapshot '+result.as_of));for(const row of result.events){const d=el('details',undefined,'history-item');d.append(el('summary',row.seq+' · '+row.event_type+' · '+row.actor+' · '+row.timestamp),el('pre',JSON.stringify(row.payload,null,2)));output.append(d);}filters=result.filters;if(result.next_after){const next=el('button','Load next page');next.onclick=async()=>{next.remove();try{await display(await api('/api/audit/events',{...filters,after:result.next_after}),true);}catch(e){$('status').textContent=e.message;}};output.append(next);}}form.onsubmit=async e=>{e.preventDefault();try{await display(await api('/api/audit/inquire',{question:input.value}));}catch(err){$('status').textContent='Use the shown inquiry template. '+err.message;}};};
$('closePreview').onclick=()=>$('preview').close();
api('/api/session').then(s=>{session=s;identity();}).catch(()=>show('login'));
